"""Safe-ish Pytest runner that executes generated HTTP checks in a temporary directory.

The runner does not accept arbitrary Python source through the public API. It only
renders a fixed pytest template from validated HttpTestSpec objects, which keeps
the demo useful without turning the service into a general remote-code endpoint.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from .execution_models import HttpTestSpec, PytestExecutionResult


def render_pytest_module(
    specs: list[HttpTestSpec],
    base_url: str,
    timeout_seconds: float = 8.0,
    verify_tls: bool = True,
) -> str:
    payload = [spec.model_dump() for spec in specs]
    payload_json = json.dumps(payload, ensure_ascii=False)
    return f'''"""Auto-generated by Req2Test Agent. Do not edit manually."""
import json

import httpx
import pytest

BASE_URL = {base_url!r}
REQUEST_TIMEOUT = {float(timeout_seconds)!r}
VERIFY_TLS = {bool(verify_tls)!r}
SPECS = json.loads({payload_json!r})


def _assert_contains(actual, expected, path="$"):
    if isinstance(expected, dict):
        assert isinstance(actual, dict), f"{{path}} expected object, got {{type(actual).__name__}}"
        for key, value in expected.items():
            assert key in actual, f"{{path}}.{{key}} missing"
            _assert_contains(actual[key], value, f"{{path}}.{{key}}")
        return
    if isinstance(expected, list):
        assert isinstance(actual, list), f"{{path}} expected list, got {{type(actual).__name__}}"
        assert len(actual) >= len(expected), f"{{path}} expected at least {{len(expected)}} items"
        for index, value in enumerate(expected):
            _assert_contains(actual[index], value, f"{{path}}[{{index}}]")
        return
    assert actual == expected, f"{{path}} expected {{expected!r}}, got {{actual!r}}"


@pytest.mark.parametrize("spec", SPECS, ids=[item["case_id"] for item in SPECS])
def test_generated_http_case(spec):
    with httpx.Client(timeout=REQUEST_TIMEOUT, verify=VERIFY_TLS, follow_redirects=True) as client:
        response = client.request(
            spec["method"],
            BASE_URL + spec["path"],
            headers=spec.get("headers") or {{}},
            params=spec.get("query") or {{}},
            json=spec.get("json_body"),
        )
    assert response.status_code == spec["expected_status"]
    expected_json = spec.get("expected_json_contains") or {{}}
    if expected_json:
        _assert_contains(response.json(), expected_json)
    for expected_text in spec.get("expected_text_contains") or []:
        assert expected_text in response.text
'''


def _count_summary(output: str, label: str) -> int:
    matches = re.findall(rf"(\d+)\s+{label}", output)
    return int(matches[-1]) if matches else 0


class PytestRunnerTool:
    """Render validated API specs into pytest and execute them with a hard timeout."""

    name = "pytest_runner"

    def __init__(self, timeout_seconds: int = 30) -> None:
        self.timeout_seconds = timeout_seconds

    def invoke(
        self,
        specs: list[HttpTestSpec],
        base_url: str,
        request_timeout_seconds: float = 8.0,
        verify_tls: bool = True,
    ) -> PytestExecutionResult:
        if not specs:
            return PytestExecutionResult(
                passed=True,
                exit_code=0,
                duration_ms=0.0,
                stdout="没有可执行 HTTP 用例，已跳过 Pytest。",
                generated_test_file=None,
            )

        source = render_pytest_module(
            specs,
            base_url=base_url,
            timeout_seconds=request_timeout_seconds,
            verify_tls=verify_tls,
        )
        started = time.perf_counter()

        with tempfile.TemporaryDirectory(prefix="req2test-pytest-") as temp_dir:
            test_path = Path(temp_dir) / "test_req2test_generated.py"
            test_path.write_text(source, encoding="utf-8")
            env = os.environ.copy()
            env.setdefault("PYTEST_DISABLE_PLUGIN_AUTOLOAD", "1")
            try:
                completed = subprocess.run(
                    [sys.executable, "-m", "pytest", "-q", str(test_path)],
                    cwd=temp_dir,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout_seconds,
                    env=env,
                    check=False,
                )
                duration_ms = round((time.perf_counter() - started) * 1000, 2)
                combined = f"{completed.stdout}\n{completed.stderr}"
                passed_count = _count_summary(combined, "passed")
                failed_count = _count_summary(combined, "failed")
                error_count = _count_summary(combined, "error") + _count_summary(combined, "errors")
                return PytestExecutionResult(
                    passed=completed.returncode == 0,
                    exit_code=completed.returncode,
                    duration_ms=duration_ms,
                    passed_count=passed_count,
                    failed_count=failed_count,
                    error_count=error_count,
                    stdout=completed.stdout[-8000:],
                    stderr=completed.stderr[-4000:],
                    generated_test_file=test_path.name,
                )
            except subprocess.TimeoutExpired as exc:
                duration_ms = round((time.perf_counter() - started) * 1000, 2)
                stdout = exc.stdout.decode() if isinstance(exc.stdout, bytes) else (exc.stdout or "")
                stderr = exc.stderr.decode() if isinstance(exc.stderr, bytes) else (exc.stderr or "")
                return PytestExecutionResult(
                    passed=False,
                    exit_code=124,
                    duration_ms=duration_ms,
                    error_count=1,
                    stdout=stdout[-8000:],
                    stderr=(stderr + f"\nPytest 超过 {self.timeout_seconds}s 被终止")[-4000:],
                    generated_test_file=test_path.name,
                )
