"""Shared visual contract for product headers outside the workbench shell."""

SHARED_HEADER_CSS = r"""
.product-header{position:sticky;top:18px;z-index:40;width:min(calc(100% - 36px),1400px);height:64px;margin:18px auto 0;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 24px;border:1px solid rgba(255,255,255,.74);border-radius:16px;background:rgba(241,245,247,.68);box-shadow:0 14px 40px rgba(27,39,54,.08),inset 0 1px 0 rgba(255,255,255,.85);backdrop-filter:blur(18px) saturate(130%);-webkit-backdrop-filter:blur(18px) saturate(130%)}
.product-header .product-wordmark{font-family:Inter,-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,"PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif;font-size:16px;font-weight:800;line-height:normal;letter-spacing:.12em}.product-header .product-wordmark b{color:#5f7fa8}
.product-header .product-nav{justify-self:center;display:flex;align-items:center;gap:38px}.product-header .product-nav a{position:relative;font-family:Inter,-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,"PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif;font-size:15px;font-weight:650;line-height:normal;letter-spacing:.055em;color:#48515d;white-space:nowrap}.product-header .product-nav a:after{content:"";position:absolute;left:0;right:100%;bottom:-8px;height:1px;background:#12171f;transition:right .25s ease-out}.product-header .product-nav a:hover:after,.product-header .product-nav a.active:after{right:0}
.product-header .product-account{justify-self:end;display:flex;align-items:center;gap:18px;font-family:Inter,-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,"PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif;font-size:12px;font-weight:700;line-height:normal;letter-spacing:.06em;white-space:nowrap}.product-header .product-account button,.product-header .product-account a{font-family:inherit;font-size:12px;font-weight:700;line-height:normal;letter-spacing:.06em;color:#46515e}
@media(max-width:1050px){.product-header .product-nav{gap:12px}}@media(max-width:800px){.product-header{grid-template-columns:1fr auto}.product-header .product-nav{display:none}.product-header .product-account{grid-column:2}}
"""
